apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'user-service'
      static_configs:
      - targets: ['user-service:8080']
      metrics_path: /metrics
    - job_name: 'ticket-service'
      static_configs:
      - targets: ['ticket-service:8081']
      metrics_path: /metrics
    - job_name: 'ai-service'
      static_configs:
      - targets: ['ai-service:8082']
      metrics_path: /metrics
    - job_name: 'notification-service'
      static_configs:
      - targets: ['notification-service:8083']
      metrics_path: /metrics